Resources:
  CognitoUserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      MfaConfiguration: 'OFF'
      UserPoolName: ${self:custom.userPoolName}
      AutoVerifiedAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Mutable: true
          Required: true
        - Name: display_name
          Mutable: true
          AttributeDataType: String
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: False
          RequireNumbers: True
          RequireSymbols: False
          RequireUppercase: True

  CognitoUserPoolClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Properties:
      ClientName: ${self:custom.userPoolClientName}
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - https:/localhost/app/auth/callback
      DefaultRedirectURI: https:/localhost/app/auth/callback
      RefreshTokenValidity: 365