Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: type
          AttributeType: S
        # - AttributeName: email
        #   AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      GlobalSecondaryIndexes:
        - IndexName: TypeSkIndex
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        # - IndexName: TypeEmailIndex
        #   KeySchema:
        #     - AttributeName: type
        #       KeyType: HASH
        #     - AttributeName: email
        #       KeyType: RANGE
        #   Projection:
        #     ProjectionType: ALL