name: Deploy Auth (service)

on:
  push:
    branches:
      - main
      - staging
    paths:
      - "services/auth/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd services/auth && sls deploy --stage production"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CI: true